"""empty message

Revision ID: 39279d2a13d6
Revises: f2d7bd63b915
Create Date: 2023-06-07 16:46:26.508682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39279d2a13d6'
down_revision = 'f2d7bd63b915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ColaboradorOnboarding',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('IdPlan', sa.Integer(), nullable=True),
    sa.Column('IdColaborador', sa.Integer(), nullable=True),
    sa.Column('ResultadoEvaluacion1', sa.Float(), nullable=True),
    sa.Column('ResultadoEvaluacion2', sa.Float(), nullable=True),
    sa.Column('FechaEvaluacion1', sa.DateTime(), nullable=True),
    sa.Column('FechaEvaluacion2', sa.DateTime(), nullable=True),
    sa.Column('ComentarioPuntosFuertes1', sa.String(length=300), nullable=True),
    sa.Column('ComentarioPuntosFuertes2', sa.String(length=300), nullable=True),
    sa.Column('ComentarioPuntosDesarrollar1', sa.String(length=300), nullable=True),
    sa.Column('ComentarioPuntosDesarrollar2', sa.String(length=300), nullable=True),
    sa.Column('ComentarioEvaluador1', sa.String(length=300), nullable=True),
    sa.Column('ComentarioEvaluador2', sa.String(length=300), nullable=True),
    sa.Column('ComentarioEvaluado1', sa.String(length=300), nullable=True),
    sa.Column('ComentarioEvaluado2', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['IdColaborador'], ['Colaborador.Id'], ),
    sa.ForeignKeyConstraint(['IdPlan'], ['Plan.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('ColaboradorActitud',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('IdActitud', sa.Integer(), nullable=True),
    sa.Column('IdColaboradorOnboarding', sa.Integer(), nullable=True),
    sa.Column('ResultadoEvaluacion1', sa.Float(), nullable=True),
    sa.Column('ResultadoEvaluacion2', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['IdActitud'], ['PlanActitud.Id'], ),
    sa.ForeignKeyConstraint(['IdColaboradorOnboarding'], ['ColaboradorOnboarding.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('ColaboradorObjetivo',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('IdObjetivo', sa.Integer(), nullable=True),
    sa.Column('IdColaboradorOnboarding', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['IdColaboradorOnboarding'], ['ColaboradorOnboarding.Id'], ),
    sa.ForeignKeyConstraint(['IdObjetivo'], ['PlanObjetivo.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('ColaboradorRecurso',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('IdRecurso', sa.Integer(), nullable=True),
    sa.Column('IdColaboradorOnboarding', sa.Integer(), nullable=True),
    sa.Column('Entregado', sa.Integer(), nullable=True),
    sa.Column('FechaEntregado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['IdColaboradorOnboarding'], ['ColaboradorOnboarding.Id'], ),
    sa.ForeignKeyConstraint(['IdRecurso'], ['Recurso.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('ColaboradorActividad',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('IdActividad', sa.Integer(), nullable=True),
    sa.Column('IdColaboradorOnboarding', sa.Integer(), nullable=True),
    sa.Column('ResultadoEvaluacion1', sa.Float(), nullable=True),
    sa.Column('ResultadoEvaluacion2', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['IdActividad'], ['PlanActividad.Id'], ),
    sa.ForeignKeyConstraint(['IdColaboradorOnboarding'], ['ColaboradorOnboarding.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('Actividad')
    op.drop_table('Actitud')
    op.drop_table('Objetivo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Objetivo',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Nombre', mysql.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('Actitud',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Nombre', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('Descripcion', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('Peso', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('Actividad',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Nombre', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('IdObjetivo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['IdObjetivo'], ['Objetivo.Id'], name='Actividad_ibfk_1'),
    sa.PrimaryKeyConstraint('Id'),
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.drop_table('ColaboradorActividad')
    op.drop_table('ColaboradorRecurso')
    op.drop_table('ColaboradorObjetivo')
    op.drop_table('ColaboradorActitud')
    op.drop_table('ColaboradorOnboarding')
    # ### end Alembic commands ###
