"""empty message

Revision ID: 4614dcf64fdc
Revises: 
Create Date: 2023-06-06 16:32:28.587569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4614dcf64fdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Recurso',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Descripcion', sa.String(length=150), nullable=True),
    sa.Column('Tipo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Recurso')
    # ### end Alembic commands ###
