"""empty message

Revision ID: 639eb5c1e8e3
Revises: f6d20f78dd47
Create Date: 2023-06-06 22:03:29.916682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '639eb5c1e8e3'
down_revision = 'f6d20f78dd47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PlanActitud', sa.Column('Nombre', sa.String(length=150), nullable=True))
    op.add_column('PlanActitud', sa.Column('Descripcion', sa.String(length=150), nullable=True))
    op.add_column('PlanActitud', sa.Column('Peso', sa.Float(), nullable=True))
    op.drop_constraint('PlanActitud_ibfk_1', 'PlanActitud', type_='foreignkey')
    op.drop_column('PlanActitud', 'IdActitud')
    op.add_column('PlanObjetivo', sa.Column('Nombre', sa.String(length=150), nullable=True))
    op.drop_constraint('PlanObjetivo_ibfk_1', 'PlanObjetivo', type_='foreignkey')
    op.drop_column('PlanObjetivo', 'IdObjetivo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PlanObjetivo', sa.Column('IdObjetivo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('PlanObjetivo_ibfk_1', 'PlanObjetivo', 'Objetivo', ['IdObjetivo'], ['Id'])
    op.drop_column('PlanObjetivo', 'Nombre')
    op.add_column('PlanActitud', sa.Column('IdActitud', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('PlanActitud_ibfk_1', 'PlanActitud', 'Actitud', ['IdActitud'], ['Id'])
    op.drop_column('PlanActitud', 'Peso')
    op.drop_column('PlanActitud', 'Descripcion')
    op.drop_column('PlanActitud', 'Nombre')
    # ### end Alembic commands ###
