"""empty message

Revision ID: f2d7bd63b915
Revises: 639eb5c1e8e3
Create Date: 2023-06-06 22:06:08.732144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d7bd63b915'
down_revision = '639eb5c1e8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PlanActividad',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('IdPlan', sa.Integer(), nullable=True),
    sa.Column('IdObjetivo', sa.Integer(), nullable=True),
    sa.Column('Nombre', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['IdObjetivo'], ['PlanObjetivo.Id'], ),
    sa.ForeignKeyConstraint(['IdPlan'], ['Plan.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PlanActividad')
    # ### end Alembic commands ###
